const NUMBER_OF_USERS = 50;
const NUMBER_OF_GROUPS = 10000;
const NUMBER_OF_USERS_GROUPS = 100000;
const NUMBER_OF_PRIVATE_MESSAGES = 500000;
const NUMBER_OF_GROUP_MESSAGES = 500000;

module.exports = {
  NUMBER_OF_GROUPS,
  NUMBER_OF_USERS,
  NUMBER_OF_USERS_GROUPS,
  NUMBER_OF_PRIVATE_MESSAGES,
  NUMBER_OF_GROUP_MESSAGES,
};
