version: "3.1"
name: scheme_2
volumes:
  pg_selectel:

services:
  pg_db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=Yra
      - POSTGRES_DB=postgres
    ports:
      - 5433:5433
