const NUMBER_OF_USERS = 5;
const NUMBER_OF_GROUPS = 10;
const NUMBER_OF_USERS_GROUPS = 7;
const NUMBER_OF_MESSAGES = 1000;
const NUMBER_OF_IMAGES = 40;

module.exports = {
  NUMBER_OF_GROUPS,
  NUMBER_OF_USERS,
  NUMBER_OF_USERS_GROUPS,
  NUMBER_OF_MESSAGES,
  NUMBER_OF_IMAGES,
};
