const NUMBER_OF_USERS = 500;
const NUMBER_OF_GROUPS = 2000;
const NUMBER_OF_USERS_GROUPS = 40000;
const NUMBER_OF_MESSAGES = 2000000;

module.exports = {
  NUMBER_OF_GROUPS,
  NUMBER_OF_USERS,
  NUMBER_OF_USERS_GROUPS,
  NUMBER_OF_MESSAGES,
};
