const NUMBER_OF_USERS = 50;
const NUMBER_OF_GROUPS = 100;
const NUMBER_OF_USERS_GROUPS = 100;
const NUMBER_OF_MESSAGES = 100;
const NUMBER_OF_IMAGES = 100;

module.exports = {
  NUMBER_OF_GROUPS,
  NUMBER_OF_USERS,
  NUMBER_OF_USERS_GROUPS,
  NUMBER_OF_MESSAGES,
  NUMBER_OF_IMAGES,
};
